config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts do
    resources :comments
  end
  root to: 'posts#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }


end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  validates :title, :body, presence: true
  has_one_attached :photo
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]
  before_action :authorize_user!, only: %i[ edit update destroy ]


  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json


  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :photo)
    end

    def authorize_user!
      redirect_back fallback_location: root_path, alert: 'Error' unless current_user == @post.user
    end
  end

app/helpers/posts_helper.rb
module PostsHelper
  def display_index_post_links(post)
    capture do
      concat content_tag( :td, link_to( 'Show', post))
      if current_user == post.user
        concat content_tag( :td, link_to('Edit', edit_post_path(post)))
        concat content_tag( :td, link_to('Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }))
      end
    end
  end

  def display_show_post_links(post)
    capture do
      if current_user == post.user
        concat link_to 'Edit', edit_post_path(post)
        concat ' | '
      end
      concat link_to 'Back', posts_path
    end
  end
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h4 class="text-danger"><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h4>

      <ul class="list-group">
        <% post.errors.full_messages.each do |message| %>
          <li class="list-group-item list-group-item-danger"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <br>
  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control' %>
  </div>
  <div class="field">
    <%= form.file_field :photo, accept:'image/*' %>
  </div>
<br>
  <%= form.submit "Save Post", class: 'btn btn-primary' %>
  <br>
<% end %>

app/views/posts/edit.html.erb
<div class="card my-5">
  <div class="card-body">
    <h1>Edit Post</h1>

    <%= render 'form', post: @post %>

    <div class="mt-2">
      <%= link_to 'Show', @post, class: 'btn btn-info mr-2' %>
      <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger mr-2' %> # moved the destroy button from index to here (optional)
      <%= link_to 'Back', posts_path, class: 'btn btn-light' %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<h1>Posts</h1>
<br>
<%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>
<br>
<br>

<hr>
<br>

<% @posts.each do |post| %>
  <div class="card">
    <div class="card-body">
      <div class="col p-4 d-flex flex-column position-static">

      <h3 class="card-title"><%= link_to post.title, post_path(post) %></h3>
      <div class="mb-1 text-muted"><%= post.created_at.strftime('%d.%m.%Y') %></div>
      <p class="card-text"><%= truncate(post.body, length: 60) %></p>
      <strong class="d-inline-block mb-2"><%= post.user.name || 'User' %></strong>

      <%= display_index_post_links(post) %>

      </div>
    </div>
  </div>
<% end %>
</div>
<br>

app/views/posts/new.html.erb
<div class="card my-5">
  <div class="card-body">
    <h1>New Post</h1>

    <%= render 'form', post: @post %>

    <%= link_to 'Back', posts_path, class: 'btn btn-light mt-2' %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="card my-5">
  <div class="card-body">
    <h1 class="text-center"><%= @post.title %></h1>
    <hr>
    <div class="my-4">
      <%= simple_format(@post.body) %>
    </div>
    <br>
    <%= image_tag(@post.photo, width: 200) if @post.photo.attached? %>
    <br>
    <br>

    <button><%= link_to 'Back', posts_path, class: 'btn btn-light' %></button>
  </div>
</div>
<div class="card my-1">
  <div class="card-body">
    <h3 class="font-weight-bold">Comments</h3>
    <br>
    <hr>
    <br>
    <%= render @post.comments %>
    <br>
    <%= form_with(model: [@post, @post.comments.build]) do |f| %>
      <div class="form-group">
        <%= f.label 'New comment' %>
        <br>
       <br>
        <%= f.text_area :body, class: 'form-control' %>
      </div>
      <br>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
      <br>
    <% end %>
  </div>
</div>